version: '3'
 
services:
    illixr:
        image: hub.ncsa.illinois.edu/friedel/nvidia/cudagl:12.2.0-devel-ubuntu22.04
        privileged: true
        container_name: ${CONTAINER_NAME:-illixr-docker}
        environment:
          - DISPLAY=${DISPLAY}
          - QT_X11_NO_MITSHM=1 # for QT applications
        build:
            context: ./src
            args:
                USER: illixr
                PASSWORD: illixr
                illixr_nproc: ${PARALLEL_CORES}
        hostname: illixr-docker
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        deploy:
            resources:
                reservations:
                    devices:
                    devices:
                      - capabilities: [gpu]
